name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 1.1.1
author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  dio: ^4.0.0
  overlay_support: 1.2.1
  rxdart: ^0.27.1

  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  package_info: ^2.0.2
  share: ^2.0.4
  chopper: ^4.0.1

#Dummy classes
  collection: ^1.15.0
flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.alice
        pluginClass: Alice
      ios:
        pluginClass: Alice
